### ISSUE TITLE
Update the XMPP logo

### ISSUE THREAD

**Issue by Neustradamus** [chat-sdk/XMPPFramework#1]
Can you update the XMPP logo on https://chatsdk.co/downloads/xmpp-chat-sdk-for-ios/ and maybe other?
The XMPP logo has been updated in 2017.

Source:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

**Comment by bensmiley** [comment]
@Neustradamus The logo looks the same to me! What is the actual difference?

**Comment by Neustradamus** [comment]
Look the file history on Wikipedia ^^

**Comment by Neustradamus** [comment]
Any news?

**Comment by Neustradamus** [comment]
@bensmiley Have you updated the logo?
Have you seen the change?

**Comment by Neustradamus** [comment]
@bensmiley: Please compare the old and the new, open your eyes:
Old: https://upload.wikimedia.org/wikipedia/commons/archive/9/95/20180322231103%21XMPP_logo.svg
New: https://upload.wikimedia.org/wikipedia/commons/9/95/XMPP_logo.svg

Thanks in advance.

**Comment by Neustradamus** [comment]
@bensmiley Any news?

**Comment by bensmiley** [comment]
Yes, It's updated. Out of interested, why are you concerned about the old logo being used?

**Comment by Neustradamus** [comment]
Only to have the good logo ;)

**Comment by Neustradamus** [comment]
@bensmiley: Can you update a new time?

There were 2 changes in the XMPP logo, please look here:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

Old version, there was a problem: https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png
